### PR TITLE
Weather App

### PR DESCRIPTION
**Pull request by Eshy10**
# Project: Weather App

Added : 
 - All HTML to DOM all in their modules
 - Use async/await in fetching data from Api
- Display the data from the Api
- Icons to show weather conditions
- Functionality to convert Celsius to Fahrenheit
 - Webpack
 - Fixed all linting errors! 

[Live Demo Link](https://sharp-mahavira-246fb5.netlify.app/)

### CODE REVIEW

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Changes Required :clap: 
You have done an amazing job with this project. You are basically done with most requirements. We have one thing to fix so we can merge this PR.
- [x]  add a toggle button to change temperature units from `celcius` to `fahrenheit` and vice-versa.
#### Optional: Load a default city's weather. Right now the UI doesn't show any data until someone searches for their city. I think the UX can be improved by loading data.

### Martin Afani

**Comment by Eshy10** [comment]
@whiz25  when you click on the temperature, it changes from Celsius to Fahrenheit

**Comment by whiz25** [comment]
> @whiz25 when you click on the temperature, it changes from Celsius to Fahrenheit

Well, how does the user know of this functionality? It's better to have a toggle button because it's visible and clear to the user.

**Review by Torres-ssf — APPROVED** [review]
### Project Approved :+1: 
Hi @Eshy10 
Nicely done in this project, I really liked your UI :clap: 
Good luck with the next one.

Happy Coding :computer: 
**Sergio Torres**

**Pull request merged**
